Repository pluralsight/classic-design-system, pull requests merged in 2018-10, with the labels that each got.

#272 dropdown: Close on outside click
  packages/dropdown/src/css/index.js
  packages/dropdown/src/react/index.js
Labels: enhancement

#269 drawer: allow custom aria-label
  packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
  packages/drawer/src/react/index.js
  packages/drawer/stories/index.js
Labels: enhancement

#279 dropdown: increase dropdown overlay z-index
  packages/dropdown/src/css/index.js
Labels: bug

#280 docs: ✏️ update references to a renamed slack channel
  packages/site/pages/contribute/code.js
  packages/site/pages/contribute/components.js
  packages/site/pages/contribute/index.js
Labels: site

#284 textinput: fix focus ring not showing
  packages/textinput/package.json
  packages/textinput/src/css/index.js
  packages/textinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
Labels: bug

#281 Errors: Low contrast in light theme (below WCAG contrast ratio)
  packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
  packages/errors/src/react/heading.js
Labels: bug, regression

#286 text.p: no default color
  packages/text/src/react/p.js
Labels: bug

#296 site: encourage a title props when using a Button without a label
  packages/site/pages/components/button.js
Labels: site

#297 button: update focus styles to allow transparent backgrounds
  packages/button/.storybook/center-decorator.js
  packages/button/.storybook/config.js
  packages/button/src/css/index.js
  packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
  packages/button/src/react/__specs__/storyshots.spec.js
  packages/button/stories/index.js
Labels: bug

#305 storybook-addon-theme: remove Button circular dependency
  packages/storybook-addon-theme/package.json
  packages/storybook-addon-theme/src/index.js
  packages/storybook-addon-theme/src/swatch.js
  packages/storybook-addon-theme/src/theme-panel.js
Labels: enhancement

#310 lerna hoist
  commitlint.config.js
  lerna.json
  package.json
  packages/actionmenu/package.json
  packages/avatar/package.json
  packages/badge/package.json
  packages/banner/package.json
  packages/breadcrumb/package.json
  packages/build/package.json
  packages/button/package.json
  packages/card/package.json
  packages/checkbox/package.json
  packages/circularprogress/package.json
  packages/datepicker/package.json
  packages/dialog/package.json
  packages/drawer/package.json
  packages/dropdown/package.json
  packages/errors/package.json
  packages/form/package.json
  packages/halo/package.json
  packages/icon/package.json
  packages/layout/package.json
  packages/link/package.json
  packages/radio/package.json
  packages/row/package.json
  packages/site/package.json
  packages/storybook-addon-center/package.json
  packages/storybook-addon-theme/package.json
  packages/switch/package.json
  packages/tab/package.json
  packages/table/package.json
  packages/tag/package.json
  packages/text/package.json
  packages/textarea/package.json
  packages/textinput/package.json
  packages/theme/package.json
  packages/tooltip/package.json
  packages/util/package.json
  packages/viewtoggle/package.json
Labels: enhancement
